# Generated by Django 4.0 on 2023-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitulosDeLivrosPublicados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Year', models.CharField(default='', max_length=15)),
                ('Lang', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Year_INI', models.CharField(max_length=4)),
                ('Year_FIN', models.CharField(blank=True, max_length=4, null=True)),
                ('Month_INI', models.CharField(max_length=20)),
                ('Month_FIN', models.CharField(blank=True, max_length=20, null=True)),
                ('Course', models.CharField(default='', max_length=200)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Discipline', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherProductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('YEAR', models.IntegerField()),
                ('NATURE', models.CharField(blank=True, max_length=50, null=True)),
                ('INSTITUTION', models.CharField(blank=True, max_length=100, null=True)),
                ('COURSE', models.CharField(default='', max_length=100)),
                ('STUDENT', models.CharField(blank=True, max_length=100, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('SPONSOR', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Workplace', models.CharField(max_length=50)),
                ('ORCID', models.CharField(max_length=100)),
                ('Fullname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=100)),
                ('Course', models.CharField(default='', max_length=200)),
                ('Year', models.IntegerField(default=0)),
                ('Integrantes', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Proj', models.CharField(max_length=50)),
                ('YEAR_INI', models.IntegerField()),
                ('YEAR_FIN', models.IntegerField(blank=True, null=True)),
                ('Natureza', models.CharField(blank=True, max_length=50, null=True)),
                ('Integrantes', models.CharField(blank=True, max_length=200, null=True)),
                ('Cordena', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=100)),
                ('TITLE', models.CharField(blank=True, max_length=200, null=True)),
                ('YEAR', models.IntegerField(blank=True, null=True)),
                ('DOI', models.CharField(blank=True, max_length=100, null=True)),
                ('LANG', models.CharField(blank=True, max_length=50, null=True)),
                ('JOURNAL', models.CharField(blank=True, max_length=300, null=True)),
                ('ISSN', models.CharField(default='', max_length=100)),
                ('AUTHOR', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
