# Generated by Django 4.0 on 2023-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0003_capitulosdelivrospublicados_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Update',
            field=models.CharField(default='', max_length=50),
        ),
    ]
