# Generated by Django 4.0 on 2023-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0004_person_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('TITLE', models.CharField(max_length=255)),
                ('YEAR', models.IntegerField()),
                ('DOI', models.CharField(max_length=100)),
                ('LANG', models.CharField(max_length=20)),
                ('AUTHOR', models.CharField(max_length=255)),
                ('ORDER', models.CharField(max_length=50)),
                ('ORDER_OK', models.CharField(max_length=50)),
            ],
        ),
    ]
