# Generated by Django 4.0 on 2023-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0005_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulosdelivrospublicados',
            name='Nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
