# Generated by Django 4.0 on 2023-08-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0006_capitulosdelivrospublicados_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Last_Name',
        ),
    ]
