# Generated by Django 4.0 on 2023-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0008_person_full_name_person_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Fullname',
        ),
        migrations.AlterField(
            model_name='person',
            name='Full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
