# Generated by Django 4.0 on 2023-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0009_remove_person_fullname_alter_person_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Year_FIN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Year_INI',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='otherproductions',
            name='YEAR',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='YEAR_FIN',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='YEAR_INI',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='YEAR',
            field=models.CharField(max_length=30),
        ),
    ]
