# Generated by Django 4.0 on 2023-09-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0011_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Citation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='capitulosdelivrospublicados',
            name='Author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='capitulosdelivrospublicados',
            name='Lang',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='capitulosdelivrospublicados',
            name='Title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='capitulosdelivrospublicados',
            name='Year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='Discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='State',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='Cordena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Proj',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publications',
            name='LANG',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='TITLE',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='LANG',
            field=models.CharField(max_length=50),
        ),
    ]
