# Generated by Django 4.0 on 2023-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0012_person_citation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Cordena',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Integrantes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Natureza',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
